# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: hipster
profiles:
- name: uat
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
    artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here:
    # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/emailservice
      context: src/emailservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/productcatalogservice
      context: src/productcatalogservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/recommendationservice
      context: src/recommendationservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/shippingservice
      context: src/shippingservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/checkoutservice
      context: src/checkoutservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/paymentservice
      context: src/paymentservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/currencyservice
      context: src/currencyservice
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/cartservice
      context: src/cartservice/src
      docker:
        dockerfile: Dockerfile
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/frontend
      context: src/frontend
    - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/adservice
      context: src/adservice
    tagPolicy:
      gitCommit: {}
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/overlays/uat
    kubeContext: gke_shawn-demo-2022_asia-east1-a_production
- name: debug
  activation:
    - command: debug
  patches:
    - op: replace
      path: /build/artifacts/7/docker/dockerfile
      value: Dockerfile.debug

---
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: loadgenerator
requires:
  - configs: [app]
build:
  googleCloudBuild:
    diskSizeGb: 300
    machineType: N1_HIGHCPU_32
    timeout: 300s
    projectId: shawn-demo-2022
  artifacts:
  - image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/loadgenerator
    context: src/loadgenerator
