resources:
- adservice.yaml
- cartservice.yaml
- checkoutservice.yaml
- currencyservice.yaml
- emailservice.yaml
- frontend.yaml
- paymentservice.yaml
- productcatalogservice.yaml
- namespace.yaml
- redis.yaml
- recommendationservice.yaml
- shippingservice.yaml
- loadgenerator.yaml