apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/frontend
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice-uat:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice-uat:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice-uat:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice-uat:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice-uat:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice-uat:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice-uat:9555"